export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const UPDATE_INSTITUTE = 'UPDATE_INSTITUTE';
export const UPDATE_SEMESTER_GROUP = 'UPDATE_SEMESTER_GROUP';
export const UPDATE_SEMESTER_NUMBER = 'UPDATE_SEMESTER_NUMBER';
export const UPDATE_DEGREE = 'UPDATE_DEGREE';
export const UPDATE_ACADEMIC_YEAR = 'UPDATE_ACADEMIC_YEAR';
export const DELETE_CURRENT = 'DELETE_CURRENT';

export const AY_LOADED = "AY_LOADED";
export const AY_ERROR = "AY_ERROR";
export const INSTITUTES_LOADED = 'INSTITUTES_LOADED';
export const INSTITUTES_ERROR = 'INSTITUTES_ERROR';

export const PEDAGOGY_LOADED = 'PEDAGOGY_LOADED';
export const PEDAGOGY_ERROR = 'PEDAGOGY_ERROR';
export const PEDAGOGIES_LOADED = 'PEDAGOGIES_LOADED';